name: osm_example

services:
  osm-example:
    container_name: osm_example
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../:/app/
    env_file:
      - .env
    command: >
      uvicorn app.main:app 
      --host 0.0.0.0 
      --port 8000
      --reload
    tty: true
    networks:
      - osm_example_network

networks:
  osm_example_network:
    driver: bridge